---

- name: Download distribution tarball
  get_url:
    url="http://eclipse.org/downloads/download.php?file=/jetty/{{ jetty_version }}/dist/jetty-distribution-{{ jetty_version }}.tar.gz&r=1"
    dest={{ jetty_src_dir }}
  become: yes
  tags:
    - jetty

- name: Create group
  group:
    name={{ jetty_group_name }}
    state=present
    system=yes
  when: jetty_group_create
  become: yes
  tags:
    - jetty

- name: Create user
  user:
    name={{ jetty_user_login }}
    state=present
    comment='Jetty Web Server'
    createhome=no
    group={{ jetty_group_name }}
    home={{ jetty_user_homedir }}
    shell=/usr/sbin/nologin
    system=yes
  when: jetty_user_create
  become: yes
  tags:
    - jetty

- name: Unpack distribution
  unarchive:
    src="{{ jetty_src_dir }}/jetty-distribution-{{ jetty_version }}.tar.gz"
    dest="{{ jetty_dst_dir}}"
    creates="{{ jetty_dst_dir}}/jetty-distribution-{{ jetty_version }}"
    copy=no
  become: yes
  tags:
    - jetty

- name: Chown jetty directory to jetty user
  file:
    path="{{ jetty_dst_dir }}/jetty-distribution-{{ jetty_version }}"
    state=directory
    recurse=yes
    owner={{ jetty_user_login }}
    group={{ jetty_group_name }}
  become: yes
  tags:
    - jetty

- name: Create symbolic link to distribution
  file:
    src="{{ jetty_dst_dir }}/jetty-distribution-{{ jetty_version}}"
    dest={{ jetty_dst_dir }}/jetty
    state=link
  become: yes
  tags:
    - jetty

- name: Create symbolic link to logs
  file:
    src="{{ jetty_dst_dir }}/jetty/logs"
    dest=/var/log/jetty
    state=link
  become: yes
  tags:
    - jetty

- name: Create init script
  file:
    src="{{ jetty_dst_dir}}/jetty/bin/jetty.sh"
    dest=/etc/init.d/jetty
    state=link
  become: yes
  tags:
    - jetty

- name: Create default configuration file
  template:
    src=default-jetty.j2
    dest=/etc/default/jetty
    owner=root
    group=root
    mode=0644
  notify: Restart Jetty
  become: yes
  tags:
    - jetty

- name: Run and enable Jetty to start on boot
  service:
    name=jetty
    state=started
    enabled=yes
  become: yes
  tags:
    - jetty
